php_version: 7.1

rules:

  # this config needed for development stage, remove it on production
  symfony.web_config_should_not_be_present:
    enabled: false

  # application need interaction in composer install
  symfony.application_not_bootable:
    enabled: false

  # disable checking flush in loop
  doctrine.use_flush_in_loop:
    enabled: false

  # allow usage of .htaccess
  web.apache_config:
    enabled: false

php_ini: |
  extension=redis.so
